### ISSUE TITLE
[RFC] Allow to make arbitrary cluster test suite with yaml files

### ISSUE THREAD

**Issue by andll** [libra/libra#1936]
Currently cluster test has two related concepts

1) **Experiment** - you can see experiment as what is called `#[test]` in unit test. [Experiment](https://github.com/libra/libra/blob/master/testsuite/cluster-test/src/experiments/mod.rs#L36) contains set of actions and have true/false output. It's a bit more complex then just `#[test]` - it can emit performance metrics, exposes set of validators affected, but overall it is very close to a test function. Examples of experiments are  - `RebootRandomValidator`, `PerformanceBenchmarkNodesDown`, `RecoveryTime`, etc

2) **Test suite** - test suite right now is basically `Vec<Experiment>`. Currently we encode test suites as just some rust code in [suite.rs](https://github.com/libra/libra/blob/master/testsuite/cluster-test/src/suite.rs)

Proposal is to allow to encode test suites in toml files:
```
git\
  cluster_test\
     suites\
         ci_suite.yml
         perf_suite.yml
         land_hook_suite.yml
```

And then specific suite can look like:
```
land_hook_suite.yml
- RebootRandomValidators
    - repeat: 5
    - params:
       - num_instances: 3
- PerformanceBenchmarkNodesDown
    - params:
       - percent_down: 10
```
We can then parse this toml file into Vec<Experiment>.
We have some plumbing already - each experiment have parameters that implement `ExperimentParam`, and we already deserialize them with `StructOpt`, we will need to add yaml deserialization for them.

This will be helpful for few reasons:
- We already have two test suites, and going to have one more for land hook
- Research can leverage those and write more yaml files

@ankushagarwal @pdhamdhere
